# Generated by Django 4.2.11 on 2024-07-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='username',
        ),
    ]
