# Generated by Django 4.2.11 on 2024-07-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_uname_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
